name: Weekly Pageviews (Wed 10am ET)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 3"   # 10:00 AM ET during DST (EDT=UTC-4)
    # switch to "0 15 * * 3" during EST (UTC-5)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: "Agg"     # headless matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run script
        run: python WIKI/scripts/pageview_analysis.py

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add WIKI/csv_downloads WIKI/weekly_data || true
          git commit -m "Automated pageviews update (NY 10am)" || echo "No changes to commit"
          git push
