name: Weekly Pageviews (Wed 10am ET)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 3"   # 10:00 AM ET during DST (EDT = UTC-4)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: "Agg"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib
      - name: Run script
        run: |
          python wiki/scripts/your_script.py   # <-- adjust if needed
      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add wiki/csv_downloads wiki/weekly_data || true
          git commit -m "Automated pageviews update (NY 10am)" || echo "No changes to commit"
          git push
