name: Weekly Pageviews (Wed 10am ET via UTC cron)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 10 * * 3
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: "Agg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # (optional) keep this once to verify paths, then remove
      - name: Debug tree
        run: |
          pwd
          ls -R

      - name: Run script
        run: python scripts/pageview_analysis.py

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add csv_downloads weekly_data || true
          git commit -m "Automated pageviews update" || echo "No changes to commit"
          git push
