name: Weekly Pageviews (Wed 10am ET via UTC cron)

on:
  # Only scheduled runs (you can add workflow_dispatch if you want manual runs)
  schedule:
    - cron: "0 14 * * 3"   # Wed 14:00 UTC = 10:00 ET in DST, 9:00 ET in EST

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: "Agg"   # headless matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -R

      - name: Install dependencies (prefer requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f "WIKI/requirements.txt" ]; then
            pip install -r WIKI/requirements.txt
          else
            pip install selenium matplotlib
          fi

      - name: Run pageview script
        run: |
          python WIKI/scripts/pageview_analysis.py

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add WIKI/csv_downloads WIKI/weekly_data || true
          git commit -m "Automated pageviews update (scheduled)" || echo "No changes to commit"
          git push
